### PR TITLE
integrate ambient-package-update

### PR DESCRIPTION
**Pull request by fbinz**

### CODE REVIEW

**Comment by fbinz** [comment]
Observations:

- package_name should be allowed to be different from module_name (i.e. `lucide_icons` vs. `django-lucide-icons`)
- some references to ambient still exist
- generated README content too rigid (contains irrelevant references - i.e. to translation files, which don't exist in my case -, too specific installation instructions)
  - idea: maybe make this "scriptable", i.e. readme_content could contain a list of sections (heading + content)
- idea: include changelog in metadata, that get's automatically generated into docs and README.md

**Comment by GitRon** [comment]
> package_name should be allowed to be different from module_name (i.e. lucide_icons vs. django-lucide-icons)

True, I agree.

> some references to ambient still exist

Where? 😅 

> generated README content too rigid (contains irrelevant references - i.e. to translation files, which don't exist in my case -, too specific installation instructions)

True. Maybe we should make more flags to opt-out of things as a quick fix?

> idea: include changelog in metadata, that get's automatically generated into docs and README.md

The changelog will be rendered into the RTD docs automatically I think.

**Comment by fbinz** [comment]
@GitRon 

> Where? 😅

Just search for "ambient.digital" here: https://github.com/fbinz/django-lucide-icons/pull/1/files

> True. Maybe we should make more flags to opt-out of things as a quick fix?

Hm, I've been thinking a bit about this. I think an important factor of the usefulness of the ambient-package-update is a) the encoding of best-practices regarding the structure/content of a package and b) the discoverability of the available options via providing explicit datatypes (i.e. the `PackageMetadata` type). 
Maybe adding a few more fields to the `ReadmeContent` would solve this? I'm specifically thinking about this:
```python
@dataclass
class ReadmeContent:
    ... # existing fields
    translation_content: str | bool = True
    installation_content: str | bool = True
```

Where `True` means that the default will be rendered, `False` means that nothing is rendered and a `str` will replace whatever the default is.
This would also be a backwards-compatible change, since the defaults would simply be `True`.

**Comment by GitRon** [comment]
@fbinz I released a new version and fixed everything except the installation readme. I think this is somehow important and I don't want people to opt-out. Right?

**Pull request merged**
